ClientDriver: Client.o ClientDriver.o
	g++ -g -Wall -std=c++11 -o ClientDriver Client.o ClientDriver.o

ClientDriver.o: Client.cpp Client.h
	g++ -g -Wall -std=c++11 -c ClientDriver.cpp

Client.o: Client.cpp Client.h
	g++ -g -Wall -std=c++11 -c Client.cpp


